"""Vendor worlds/_id1common into an id1 world as its ``.id1common`` fallback.

Worlds generated by ap_gen_tool 2.0 (doom_1993_beta, doom_ii_beta, heretic_beta)
import the shared id1Common base world with a fallback meant for standalone
packaging::

    try:
        from worlds._id1common import id1CommonWorld
    except ImportError:
        from .id1common import id1CommonWorld

``worlds/_id1common`` is a sibling of the world dir, so shape_tree never copies
it, and a host that installs the wheel without it fails the fallback import.
This copies the library into ``<world>/id1common/`` at wheel-build time; the
package must keep that name and its ``options`` submodule. Its only third-party
import, orjson, is host-provided, so requirements are untouched.

Each id1 world's override.py re-exports TOUCHES and apply from this module.
"""
from __future__ import annotations

from pathlib import Path

FILES = ("__init__.py", "options.py", "LICENSE")
TOUCHES = [f"id1common/{name}" for name in FILES]


def apply(world_dir: Path) -> list[str]:
    source = world_dir.parent / "_id1common"
    payload = {name: (source / name).read_bytes() for name in FILES}
    target = world_dir / "id1common"
    target.mkdir(exist_ok=True)
    for name, data in payload.items():
        (target / name).write_bytes(data)
    return [f"vendored worlds/_id1common/{name} as id1common/{name}" for name in FILES]
