"""Open a PR against MultiworldGG-Index updating worlds/<slug>.json's module_location.

Workflow:
  1. Clone the Index repo (shallow) using INDEX_PR_TOKEN.
  2. Read worlds/<slug>.json. If module_location already matches the new value
     and the file is otherwise unchanged, skip the PR (no-op).
  3. Update the field, preserving every other key + 4-space indent + trailing \\n
     (matches what Phase-1 backfill produced).
  4. Push to a fresh branch update/<slug>-<world_version> on the Index repo.
  5. `gh pr create` against main, body uses the manifest_update.md template
     contents inline + the Karen checks happen automatically once the PR opens.
  6. If a PR already exists for this branch, just update the head and let the
     CI re-trigger. If a PR exists for an *older* version of this slug, leave
     it alone — the new one supersedes it but cleaning up old PRs is outside
     this script's job.

Env vars:
  INDEX_PR_TOKEN     PAT/GitHub-App token with contents:write + PR:write on Index
  INDEX_REPO         e.g. "lallaria/MultiworldGG-Index"
  CALLER_REPO        e.g. "MultiworldGG/MultiworldGG"
  WORLD_SLUG         e.g. "oot"
  WORLD_VERSION      e.g. "7.0.2"
  TAG_NAME           e.g. "module-install/7.0.2"
  GIT_USER_NAME / GIT_USER_EMAIL  committer identity for the PR-branch commit
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def env(name: str, *, required: bool = True, default: str = "") -> str:
    val = os.environ.get(name, default).strip()
    if required and not val:
        print(f"::error::missing required env var {name}", file=sys.stderr)
        sys.exit(2)
    return val


def run(*cmd: str, cwd: Path = None, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    print(f"$ {' '.join(cmd)}{f'  (cwd={cwd})' if cwd else ''}")
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        check=check,
        text=True,
        capture_output=capture,
    )


def main() -> int:
    token = env("INDEX_PR_TOKEN")
    index_repo = env("INDEX_REPO")
    caller_repo = env("CALLER_REPO")
    slug = env("WORLD_SLUG")
    world_version = env("WORLD_VERSION")
    tag = env("TAG_NAME")
    git_user_name = env("GIT_USER_NAME")
    git_user_email = env("GIT_USER_EMAIL")

    new_module_location = (
        f"git+https://github.com/{caller_repo}.git@{tag}"
    )
    pr_branch = f"update/{slug}-{world_version}"

    # 1. Clone Index repo into a temp dir.
    tmp = Path(tempfile.mkdtemp(prefix="index-pr-"))
    index_dir = tmp / "index"
    clone_url = f"https://x-access-token:{token}@github.com/{index_repo}.git"
    safe_clone_url = f"https://x-access-token:***@github.com/{index_repo}.git"
    print(f"Cloning {safe_clone_url} (depth 1)")
    run("git", "clone", "--depth", "1", clone_url, str(index_dir))

    run("git", "config", "user.name", git_user_name, cwd=index_dir)
    run("git", "config", "user.email", git_user_email, cwd=index_dir)

    manifest_path = index_dir / "worlds" / f"{slug}.json"
    if not manifest_path.is_file():
        print(f"::error::Index repo {index_repo} has no worlds/{slug}.json — refusing to add a brand new manifest from this action.")
        print("New worlds need a one-time manual PR adding worlds/<slug>.json with all required fields.")
        return 1

    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    if manifest.get("module_location") == new_module_location:
        print(f"worlds/{slug}.json already has module_location={new_module_location}; nothing to do.")
        return 0

    # Preserve key order (Python dict preserves insertion order). We only
    # rewrite module_location in place.
    manifest["module_location"] = new_module_location
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=4, ensure_ascii=False)
        f.write("\n")

    # 2. Branch + commit + push.
    run("git", "checkout", "-b", pr_branch, cwd=index_dir)
    run("git", "add", f"worlds/{slug}.json", cwd=index_dir)
    commit_message = (
        f"Update {slug} to {world_version}\n\n"
        f"module_location -> {new_module_location}\n"
        f"\n"
        f"Auto-generated by MultiworldGG/build-and-publish-action."
    )
    run("git", "commit", "-m", commit_message, cwd=index_dir)
    # Force-push so a re-run of this slug-version updates the existing branch
    # (e.g. if the action was re-triggered after a transient failure).
    run("git", "push", "--force", "origin", pr_branch, cwd=index_dir)

    # 3. Open the PR (or update body if it already exists).
    pr_title = f"[{slug}] Update to {world_version}"
    pr_body = (
        f"Auto-generated update from "
        f"[MultiworldGG/build-and-publish-action](https://github.com/MultiworldGG/build-and-publish-action).\n"
        f"\n"
        f"## Manifest update\n"
        f"\n"
        f"- **Slug:** `{slug}`\n"
        f"- **World version:** `{world_version}`\n"
        f"- **Source repo:** [{caller_repo}](https://github.com/{caller_repo})\n"
        f"- **Source tag:** [`{tag}`](https://github.com/{caller_repo}/tree/{tag})\n"
        f"- **New `module_location`:** `{new_module_location}`\n"
        f"\n"
        f"## Karen's review\n"
        f"\n"
        f"Karen's PR-review workflow will post a sticky comment with the 7-check result.\n"
        f"If any check fails, fix the underlying issue in the source repo, bump\n"
        f"`world_version`, and re-publish — this PR will be superseded by the new version.\n"
    )
    env_for_gh = {**os.environ, "GH_TOKEN": token}

    # Check whether a PR for this branch already exists.
    existing = subprocess.run(
        ["gh", "pr", "list", "--repo", index_repo, "--head", pr_branch, "--json", "number", "--state", "open"],
        env=env_for_gh,
        capture_output=True,
        text=True,
    )
    existing_pr_numbers: list[int] = []
    if existing.returncode == 0 and existing.stdout.strip():
        try:
            existing_pr_numbers = [int(p["number"]) for p in json.loads(existing.stdout)]
        except (json.JSONDecodeError, KeyError, TypeError):
            pass

    if existing_pr_numbers:
        n = existing_pr_numbers[0]
        print(f"PR #{n} already open for branch {pr_branch}; updating body.")
        subprocess.run(
            ["gh", "pr", "edit", str(n), "--repo", index_repo, "--title", pr_title, "--body", pr_body],
            env=env_for_gh,
            check=True,
        )
    else:
        print(f"Opening new PR against {index_repo}")
        subprocess.run(
            ["gh", "pr", "create",
             "--repo", index_repo,
             "--base", "main",
             "--head", pr_branch,
             "--title", pr_title,
             "--body", pr_body],
            env=env_for_gh,
            check=True,
        )

    # Cleanup. Token is in the URL; nuke the temp dir.
    shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
